version: "3.8"

services:
  wav-service:
    build: .
    ports:
      - "4552:4552"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - FLASK_ENV=production
      - EXTERNAL_BASE_URL=http://127.0.0.1:4552 # 请根据您的实际外部访问地址修改此值
    restart: unless-stopped

